name: PyPI 📦 Distribution

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [aarch64]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Set up QEMU
      #if: ${{ matrix.arch == 'aarch64' }}
      uses: docker/setup-qemu-action@v1

    - name: Build distribution 📦
      #shell: bash 
      run: |
             docker run --rm -v `pwd`/:/work dockcross/manylinux2014-aarch64 > ./dockcross-manylinux2014-aarch64 \
             bash -c 'uname -m && \
             chmod 777 ./dockcross-manylinux2014-aarch64 && \
             ls ./dockcross-manylinux2014-aarch64 && \
             file dockcross-manylinux2014-aarch64 && \
             yum install python-pip -y && \
             pip install setuptools wheel && \
             ./dockcross-manylinux2014-aarch64 bindings/python/build_wheel.sh'
       
    - uses: actions/upload-artifact@v2
      with:
         path: ${{ github.workspace }}/bindings/python/dist/*

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - name: Publish distribution 📦 to test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.testpypi_pass }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish distribution 📦 to PyPI
        if: ${{ success() }}
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_pass }}
